### ISSUE TITLE
fix: display area in Fluent Dialog

### ISSUE THREAD

**Issue by rzhang2020** [microsoft/fast-blazor#141]
# 🐛 Bug Report

When a dialog pops up, dialog cannot cover background Fluent Components.

## 💻 Repro or Code Sample
@page "/DialogPage"
<FluentDialog @ref="MyFluentDialog" id="foo" aria-label="Simple dialog" Modal="true">
    <h2>Dialog referenced to object</h2>
    <button @onclick="OnCloseModalRefButtonClick">Close dialog with component object function</button>
</FluentDialog>

<FluentDialog Hidden="ModalHidden" id="foo" aria-label="Simple dialog" Modal="true">
    <h2>Dialog referenced with variable</h2>
    <button @onclick="OnCloseModalParameterButtonClick">Close dialog updating the variable</button>
</FluentDialog>

<p>MyFluentDialog.Hidden value: @MyFluentDialog?.Hidden</p>
<p>ModalHidden value: @ModalHidden</p>

<FluentButton @onclick="OnOpenModalRefButtonClick">Open dialog with ref</FluentButton>
<FluentButton @onclick="OnOpenModalParameterButtonClick">Open dialog with variable</FluentButton>

## 🤔 Expected Behavior
Dialog should cover all background controls.

## 😯 Current Behavior
![image](https://user-images.githubusercontent.com/76229561/145522686-f6c93a53-32c0-43a4-a724-858390db292d.png)

## 🌍 Your Environment

* OS & Device: Windows 10 Pro
* Browser: Microsoft Edge, Google Chrome,
* .NET 6
* Latest FAST

**Comment by EisenbergEffect** [comment]
The reason for this is that HTML (currently) has no notion of a popup layer, a place where you can always put HTML to ensure it overlays other components. That is something we are actually working on with W3C to fix. Because our components can't them make any assumptions about how you are handling this in your own application, we don't have any special code to set z-index. To solve this in your own application, just add a z-index to the style of your dialog based on what you need for your application.

I'll create an issue to track a documentation update to clarify this.
