### ISSUE TITLE
Page background does not change after switching theme to dark

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fast-blazor#159]
# 🐛 Bug Report

We are migration our project to Microsoft fast. We have started with a simple page inside the project that display only the page header and some simple text. We put a switch theme component inside header and tried to change the backgriound color for the page.

## 💻 Repro or Code Sample

Create a simple project from the new blazor wasm template. In the navigation compoent define only 3 items. Create a new page that contains only a title and change the background color using the theme switch example on github.

## 🤔 Expected Behavior

The entire page background should change its background color.

## 😯 Current Behavior

The page background color is changed only for the portion that displays blazor components. Everything beneath the blazor components that does not have any components but is displayed on screen does not change the background color, it remains white.

## 💁 Possible Solution

I do not know a solution for this.

## 🔦 Context

We have a older version of the project that has theme change for the entire page and we cannot migrate to microsoft fast without having the same option there.

## 🌍 Your Environment

Working in Visual Studio 2022.

* OS & Device: [ Windows 10]
* Browser [Microsoft Edge]
* Version [99.0.1150.36 ]

**Comment by vnbaaij** [comment]
@chigivigi You just need to make sure that the html element directly following the <FluentDeignSystemProvider> component has a height set that takes up the whole vertical available space. If you went with the template, you probably have something like:
```
<FluentDesignSystemProvider @ref=fdsp Direction=@dir BaseLayerLuminance=@baseLayerLuminance>
    <div class="container">
...
```
Then in the css for the `container` add the rule `height: 100vh;` (instead of trying to using `%` or `px`). This is standard ccs grid code and has nothing to do with Blazor and/or the FluentUI components.

**Comment by chigivigi** [comment]
@vnbaaij thank you for your help. After adding the height value, you suggested the entire page background color has changed.
