### ISSUE TITLE
Add Color properties for Dark Theme in FluentDesignSystemProvider

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fast-blazor#251]
# 🙋 Feature Request

In fluent design system provider add base color properties for dark theme.

## 🤔 Expected Behavior

Display base colors that are defined for dark theme with base color properties in the fluent design system provider. 

## 😯 Current Behavior

Currently base colors define the light theme. It is not possible to define color for dark theme, base layer luminance changes the base color for dark theme based on the light theme.

## 🔦 Context

I have set the base colors for the accent and neutral colors to match the logo color of the firm I am working for, but those colors are defined in light theme. The firm has a dark logo and prefers to work with the app in dark theme, but in dark theme the base and accent color do not match with the colors of the logo after base layer luminance is changed.

**Comment by vnbaaij** [comment]
The design system uses specific algorithms to calculate the colors (taking into account contrast). I'm not sure if what you want/need can be done.
 
I'm transferring this to the FAST repo as that is where design system comes from. There are no changes made to the original code on the Blazor side.

**Comment by chigivigi** [comment]
link to fork code: https://github.com/chigivigi/fast-blazor/blob/main/examples/FluentUI.Demo.Shared/Pages/Button/Examples/ButtonIcon.razor

**Comment by chigivigi** [comment]
I would like to have the same accent color for dark and light theme. How can I retain the color in dark theme ?

**Comment by vnbaaij** [comment]
> I would like to have the same accent color for dark and light theme. How can I retain the color in dark theme ?

You can't if you use the design system colors (like AccentBaseColor) because those are calculated based on the luminance.
If you need to use a specific color, you would need to set it with standard CSS.

See https://www.fast.design/docs/design-systems/fast-frame#adaptive-color-system for more info on the useage of color.

**Comment by chigivigi** [comment]
On the fast design page: https://www.fast.design
I was able to set the accent color and after changing to dark mode it did not change. This is needed because of branding and accent color should be fixed on our page. Do you know how to achieve this in blazor without messing with the css?
![image](https://user-images.githubusercontent.com/30351793/204760255-d886fb47-8f9b-4f4d-86db-40aa0561f569.png)

![image](https://user-images.githubusercontent.com/30351793/204760099-4ea95246-3c2b-4fce-bc28-bbb17f3f8867.png)

**Comment by vnbaaij** [comment]
Hi @chigivigi,

I'm calling in some help from the experts from the FAST team to see if what you want to do is possible and how.

In the meantime, if you look at the sample you mention (which I believe is obsolete, but I'll leave that for the experts to answer), you can find that it is also changing the color values between light and dark mode:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/1761079/204772610-75a53ba2-0c15-4d0a-9236-7a80275bd0d1.png">
If you look at the label from this image in the DevTools you can see the background for the square is
`background-color: var(--accent-fill-rest);`.
Although it **appears** to be the same color, you can see in the DevTools it is **not**. This `--accent-fill-rest` is set to `#df402e` in dark mode and is changed to `#f45643` in light mode.

**Comment by chigivigi** [comment]
Thank you for the response, I hope that the FAST team has a solution, and the color can have at least minimal change when changing from light to dark mode and vice versa.

**Comment by bheston** [comment]
The example you found on the FAST website is an old version of the color system, and is different from the one used in the Fluent UI components. The site for understanding the use of color is https://aka.ms/fluentwebcomponents, then click on Color Explorer under Design System on the left nav.

Using the same accent color is often not desirable in both light and dark mode because there are few colors that meet contrast requirements in each. Also, the interpretation of the color is different based on the neighboring luminance. For instance, a purple/blue that might look good in light mode is hard to discern in dark:
![image](https://user-images.githubusercontent.com/47367562/204912978-aca4f849-ed6d-4b20-aee1-0f402be5cc1c.png)

I recommend reevaluating the requirements for using a single color as it will likely produce a better experience for your customers. Reference the WCAG requirements for 4.5:1 text contrast and 3:1 non-text contrast for something like the filled part of the slider.

I'm not familiar with the capabilities of incorporating JS or overriding CSS variables in Blazor, but if overriding the color recipes is not feasible you would need to adjust the CSS stylesheets for any component using accent color.

**Comment by chigivigi** [comment]
thank you for your help.
