### ISSUE TITLE
Fix: Chrome add-ins can break FluentUI components

### ISSUE THREAD

**Issue by MertUssakliMSFT** [microsoft/fast-blazor#258]
# 🐛 Bug Report

We have received a complaint from a user around how their `FluentComboBox` don't work. This was root-caused to an add-in they had, which they said they have been using for years but has caused no issues for them until this point. 

This is the Chrome add-in: https://chrome.google.com/webstore/detail/super-dark-mode/nlgphodeccebbcnkgmokeegopgpnjfkc

## 💻 Repro or Code Sample

To repro, install and enable the linked add-in, and display a markup like this: 

```
<div>
    <FluentCombobox TValue="string" Autocomplete="ComboboxAutocomplete.Inline">
        <FluentOption>a</FluentOption>
        <FluentOption>b</FluentOption>
        <FluentOption>c</FluentOption>
        <FluentOption>d</FluentOption>
        <FluentOption>e</FluentOption>
        <FluentOption>f</FluentOption>
        <FluentOption>g</FluentOption>
        <FluentOption>h</FluentOption>
        <FluentOption>i</FluentOption>
        <FluentOption>j</FluentOption>
        <FluentOption>k</FluentOption>
        <FluentOption>l</FluentOption>
        <FluentOption>m</FluentOption>
        <FluentOption>n</FluentOption>
        <FluentOption>o</FluentOption>
        <FluentOption>p</FluentOption>
        <FluentOption>q</FluentOption>
        <FluentOption>r</FluentOption>
    </FluentCombobox>
```

## 🤔 Expected Behavior

This is what I expect to see: 

![image](https://user-images.githubusercontent.com/94049942/206766885-47dd6ed3-72b2-4dce-8a78-9f0e2d5bc5e5.png)

## 😯 Current Behavior

Looks like this when the add-in is enabled: 

![image](https://user-images.githubusercontent.com/94049942/206766677-6363c27d-bc67-409f-b2df-411daf6f48a2.png)

## 💁 Possible Solution

I was not able to root-cause why the component breaks with this add-in. 

## 🔦 Context

I don't know if this issue is specific to the add-in or not. The worry is this might be a common behavior a lot of Chrome/Edge users, and fast-blazor component will not work on all of these machines.

## 🌍 Your Environment

Windows, Edge, .NET 7, Blazor WebAssembly app.

**Comment by vnbaaij** [comment]
It breaks the site because it injects custom CSS into the page... I'm not going to be able to defend against that I'm afraid. 

Also, I'm not planning to spend precious development time on that. The demo site and library come with good examples how to set up a perfectly working dark mode already. In fact, the latest version of the demo even follows the default theme set by the browser.

It is not just interfering with the Blazor components. It breaks FAST as well (see below) so it is definitely doing something sketchy witch the scripts/css of the site,
<img width="717" alt="image" src="https://user-images.githubusercontent.com/1761079/206913089-309e1276-5f1c-4cf3-b23b-3d03c6866090.png">

**Comment by vnbaaij** [comment]
I discussed this a bit more with the broader FAST team. Conclusion is we are not going to make changes to the root library to make it work with one extension which somehow breaks it. We just don't think it's possible to accommodate something like that given it's completely out of our control.
