### ISSUE TITLE
ver 1.6.0 FluentSelect TOption does not resolve

### ISSUE THREAD

**Issue by Terrence77** [microsoft/fast-blazor#260]
<PackageReference Include="Microsoft.Fast.Components.FluentUI" Version="1.6.0" />
I am using the latest 1.6.0 but I can't set the TOption parameter, it does not resolve. Net6 or 7 projects.

<ProjectReference Include="E:\source\fast-blazor\src\Microsoft.Fast.Components.FluentUI\Microsoft.Fast.Components.FluentUI.csproj" />
When I create a project and use the actual source code for the blazor fluent wrappers the TOption parameter resolves.

**Comment by vnbaaij** [comment]
Hi, there are indeed issues with the Fluent Select in version 1.6. That is why we rewrote them (also FluentListbox and FluentCombobox) for version 2.0.

The main branch contains the source of Version 2 so that explains why it works if you do it the way you described. You can install the 2.0 package (RC1) from NuGet by specifying the version when using the command line of checking 'use pre release version' in Visual Studio.
See the announcement in the Discussion forum here for more information on version 2.

**Comment by Terrence77** [comment]
Thank you for that information, Vincent.  Keep up the great work on this great package.
