### ISSUE TITLE
fix: fluent icon slot stat being positioned at end in fluent menu item

### ISSUE THREAD

**Issue by baywet** [microsoft/fast-blazor#293]
# 🐛 Bug Report

```xml
<FluentMenuItem @onclick=@GoHome>
                @Loc["Search"]
                <FluentIcon Name="@FluentIcons.Search" Slot="start" Size="@IconSize.Size24" Filled=false UseAccentColor=false />
            </FluentMenuItem>
```

Displays the icon at the end instead of at the start.

## 💻 Repro or Code Sample

https://github.com/microsoft/kiota/pull/2144

Or https://brave-cliff-0c0c93310.azurestaticapps.net/Menu, the with icon example is displaying like this even though icons should be on each side.

## 🤔 Expected Behavior

icons on start slot to be displayed before the text

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/7905502/212396487-346533bb-4509-426d-a071-62a60be9a17a.png)

## 🌍 Your Environment

* OS & Device: windows
* Browser Microsoft Edge
* .NET and FAST Version [e.g. 1.8.0] 7.0.2 and 2.0.1

Note: it used to be working properly with 1.6.0

**Comment by vnbaaij** [comment]
The issue's origin lies here (from https://www.fast.design/docs/components/menu#setup):
>`fast-menu` applies `fast-menu-item`'s `startColumnCount` property based on an evaluation of all of the `fast-menu-items` so the content text vertically aligns across all `fast-menu-items`. If any `fast-menu-item` does not have a roll of `checkbox` or `radio` or the `start` slot is not passed, `startColumnCount` is set to 0 which applies a `indent-0` class to all the `fast-menu-item`s. If any `fast-menu-item` has a roll of `checkbox` or `radio` or the `start` slot exists, `startColumnCount` is set to 1 which applies a `indent-1` class to all the `fast-menu-item`s. Or if any `fast-menu-item` has a roll of `checkbox` or `radio` and the `start` slot exists, `startColumnCount` is set to 2 which applies a `indent-2` class to all the `fast-menu-item`s.

Because we are rendering the web components indirectly (through the Blazor components) `fast-menu` doesn't know about the `fast-menu-items` when it renders (they don't exist in the DOM yet) so it can't determine the `startColumnCount`. 

As a (temporary) workaround, you can create an empty `<span slot="start"></span>` in one of the menu items. The script gets triggered then and the icons render in the right place.
