### ISSUE TITLE
fix: Templates do not include Icon changes 

### ISSUE THREAD

**Issue by AndyEdmonds** [microsoft/fast-blazor#337]
The templates do not include the project file additions or the program.cs changes required to access Icons, but icons are used by the template.

## 💁 Possible Solution

Add this to the project file.
```
	<PropertyGroup>
		<PublishFluentIconAssets>true</PublishFluentIconAssets>
		<FluentIconSizes>24,32</FluentIconSizes>
		<FluentIconVariants>Filled,Regular</FluentIconVariants>
	</PropertyGroup>
```

modify these lines in program.cs

```
LibraryConfiguration config = new(ConfigurationGenerator.GetIconConfiguration(), ConfigurationGenerator.GetEmojiConfiguration());
builder.Services.AddFluentUIComponents(config);
```

**Comment by vnbaaij** [comment]
We don't want to 'force' using icons when using the template. What I'll do for a next version of both package and templates is to include/change the used icon in the template to one in the default set that us always available in the library

**Comment by AndyEdmonds** [comment]
Hi Vincent, I imagine most apps will use icons, though probably not emojis. 
At the moment, if you use Icons, upgrading to the most recent version is quite disruptive. It's not clear there are breaking changes until you dig into this site. As for the templates, it would be good to mirror the existing Blazor templates, including authorization and the option of an added server for Wasm.

**Comment by vnbaaij** [comment]
Hi Andy, we decided to not include the icons by default because some were having issues/not happy with the fact that you get several thousand files in your published application. Fortunately we are now able to trim that with the new settings but we still want it to be an explicit choice by the developer.
 You are right it is a bit of a hassle if you are using icons already but that is a one off thing. Where should we publish these kind of (breaking) changes to make them more discoverable?
On the templates, I'll see if we can make them more up to park withe the standard ones.

**Comment by vnbaaij** [comment]
Templates have been updated with `.csproj` additions and include icons/emoji usage comments in code in #1e7935f4. Version 2.0.4 NuGet Templates package has been published
