### ISSUE TITLE
Fluent DataGrid columns do not respect max width settings for Fluent Datagrid

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fast-blazor#342]
# 🐛 Bug Report

We use a fluent datagrid with GridTemplateColumns property definied.
When we set the max width for the datagrid, the columns of the datagrid do not resize and they are displayed out of bounds of the datagird.

## 💻 Repro or Code Sample

On the demo site there are Fluent Datagrid examples that use GridTemplateColumns property. If you set the max width for the Fluent Datagrid to 300px the column will not resize and will go out of bounds of the datagrid.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/30351793/223439271-1ce7a17f-0088-4f14-a481-87608925711c.png)

## 🤔 Expected Behavior

The columns change their width so they can be displayed inside the fluent datagrid when the max width setting is set.

## 😯 Current Behavior

The columns leave the bounds of the fluent datagrid and are breaking the display of the page. If the window is smaller they are not even displayed on the page and you have to use horizontal scrollbar to see them.

## 🔦 Context

The users have a hard time editing the values inside rows when they have to scroll left and right to see the column they need to edit inside the fluent datagrid.

## 🌍 Your Environment

Visual studio 2022
WIndows 11
Microsoft Edge latest version

**Comment by vnbaaij** [comment]
This happens because the grid in the example has a fixed width (500px) set on itself:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/1761079/223696988-7231d3ca-6a13-44f8-b5fc-2253407984bb.png">

If you remove the witdh on the grid, it follows what was set in the containing element , including margin, padding, etc.:

<img width="174" alt="image" src="https://user-images.githubusercontent.com/1761079/223697258-51aa8ab5-ccc5-409a-811c-ad3b82ecae10.png">
