### ISSUE TITLE
Cannot read property 'indexOf' of undefined when browsing to sample Blazor component bindings page

### ISSUE THREAD

**Issue by danroth27** [microsoft/fast-blazor#41]
Repro steps:

- Run the FluentUIServerSample
- Browse to the Blazor component bindings page

Error in browser console:

```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at check_for_ASP (onloadwff.js:71)
    at chk_form_has_password (onloadwff.js:71)
    at checkForLoginForm (onloadwff.js:71)
    at onloadwff.js:71
```

**Comment by EddyHaigh** [comment]
Looks like this is an error caused by a chrome extension, specifically Last Pass. If you disable the extension it shouldn't throw.
![image](https://user-images.githubusercontent.com/23223991/119572074-1f2c0280-bdaa-11eb-9bce-ab8dd98f9927.png)
This issue a known problem: https://github.com/lastpass/lastpass-cli/issues/428

**Comment by EisenbergEffect** [comment]
Good find @EddyHaigh !
