### ISSUE TITLE
Add DetailsList control from Fluent UI to Blazor

### ISSUE THREAD

**Issue by hkusulja** [microsoft/fast-blazor#47]
Hello,
We are using ASP.NET 5 with Blazor WASM for frontend and internal business applications.
We are missing Fluent UI controls, especially some grid control like - DetailsList - https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist

I hope this fast-blazor GitHub will develop this control as soon as possible. So we can put data in DetailsList and sort it, filter etc., everything that Fluent UI web control already has, but we need it in Blazor WASM.

Maybe this will be the biggest and most complex control of having in FATS-Blazor , (due to futures) but this is what is needed and commonly used.

**Comment by EisenbergEffect** [comment]
@chrisdholt Can you address the how we would handle the request for DetailsList? It looks like it's the same as our data grid but potentially with some additional features.

**Comment by hkusulja** [comment]
Any progress in past month on this? Basically, this is the same or similar to #46

**Comment by EisenbergEffect** [comment]
We're right in the middle of a major update to FAST and Fluent. That's taking most of our time right now. We hope to have that wrapped up soon. After that, we'll be updating the Blazor wrappers based on the latest components as well as adding in missing components. Thanks for your patience!

**Comment by sharp-summit** [comment]
This is a very useful feature,I'm looking forward to it, good luck!👍

**Comment by hkusulja** [comment]
@EisenbergEffect thank you for the update, however, days are passing, can you be little more specific on estimation of timeline except "soon" , just to align expectations. Thank you

**Comment by EisenbergEffect** [comment]
Apologies for the ambiguity. We had some uncertainty regarding the vNext Fluent release work we were doing. That's been figured out now and the release is out. We've also had quite a few team members take vacation over the last few weeks (well deserved I might add) and folks are now coming back from that. In terms of timeline, I hope that we can start that update here this week or next week. Once that's done, then it should be easier for us to address issues specifically in the Blazor wrappers here in an ongoing fashion.

**Comment by hkusulja** [comment]
Ok, since you mentioned "release is out". It is strange since no source code is visible here in repo on github, also if you can reference nuget package link with released version? tx

**Comment by EisenbergEffect** [comment]
Let me provide some clarification. The release of the underlying web components is out. That code is in the FAST and Fluent UI monorepos. That is on NPM and available on CDN. The Blazor wrappers for those web components in this repo are not yet updated to the new version. We hope to start that work this week and get a release out on Nuget as soon as that is done.

**Comment by hkusulja** [comment]
Hello, how is the progress going for nuget release? where we can track progress?

**Comment by EisenbergEffect** [comment]
We had a Nuget release last week. We also published the release here on GitHub with some brief release notes this week.

**Comment by hkusulja** [comment]
@EisenbergEffect thank you for nuget update, but this original question / task still remains, what about DetalisList component from Fluent UI to this repo / nuget? I also do not see your DataGrid ...

**Comment by EisenbergEffect** [comment]
I have to defer to @chrisdholt regarding the DetailsList. I think this is handled by our DataGrid though. We can certainly work on adding a wrapper for that. @vnbaaij Do you have any time to help us out by putting together a wrapper for the DataGrid?

**Comment by vnbaaij** [comment]
I can certainly take a look but not before end of the month. Enjoying my vacation now and no PC in the neighborhood

Met vriendelijke groet,

Vincent Baaij
Egmondland 28
2635MW Den Hoorn
06 421 412 28

________________________________

**Comment by EisenbergEffect** [comment]
Thanks @vnbaaij ! If my team can get to it before then, we'll try. If not, having you pick this up once you are back in office would be a tremendous help.

**Comment by vnbaaij** [comment]
First steps can be seen here: https://github.com/vnbaaij/fast-blazor/tree/fluent-data-grid

**Comment by hkusulja** [comment]
@vnbaaij thank you for progress, just to clarify, requested DetailsList component depends on Data Grid component(s)?

**Comment by EisenbergEffect** [comment]
@hkusulja I believe you should be able to build a details list experience with the Fluent DataGrid Web Component. Can you share any particular features that are missing that would make that difficult for you? We can try to help you find solutions or build new features to accommodate key scenarios. 

There are a couple of things that likely make all of this confusing:

* Fluent is a design system with many implementations. Each implementation strives to be as close as possible to the gold standard for the design. But, each implementation does so in a way that is idiomatic for the platform it is targeting. As a result, some differences will likely occur in naming, APIs, or even appearance. For example, React has an Image component, but the Web Components do not (and likely will never) have such a component. Why? Because React requires everything to be a React component for ergonomics, interop, and sometimes styling. Web Components do not have that limitation and can thus use the native HTML `img` element instead.
* Fluent is a design system with many versions. What you are currently viewing on the referenced web site is an old version of Fluent. The best way to see the latest version of Fluent is to look at Windows 11. All implementations of Fluent are attempting to align to this latest version. Some implementations are further along than others. The Web Components implementation is closer than the React version that you referenced. In a matter of days we expect to ship our updated Web Components to fully align with the latest design, making the Web Components the most up-to-date implementation of Fluent, second only to Windows 11, and the only up to date version for the web.

I apologize if this has been confusing. There are many pieces in motion at once and different teams are at different places in their efforts to update implementations and align to the latest design. Documentation is also a work-in-progress, which is why you are seeing some of the discrepancies in components. That should all work itself out. Unfortunately, I can't give you more information than I have here. My team only works on the Web Component implementations. We do not control the design language, the React components, or the currently published documentation. Please rest assured that I have provided copious amounts of feedback to the other teams on how confusing this has been for customers. Please accept my humble apology and know that our team remains committed to trying to address these issues and trying to influence other teams towards a more favorable outcome for you and all Microsoft customers looking to build Fluent experiences.

**Comment by hkusulja** [comment]
So, again, we are building Blazor Web Assembly app, and want to have UI, like Microsoft Fluent UI web components.
We need control, that is most like https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist , details list.
The point of the control is data table / grid / details list, (whatever name you want) :P , to be able to display, sort, filter , group the content / rows. You can look the SharePoint List as example also, or mentioned original Fluent UI. It should support icons, dates, strings, numbers. Multiple/modal selection also, as referenced from Fluent UI..

**Comment by EisenbergEffect** [comment]
Good news! A PR is up for the DataGrid wrapper https://github.com/microsoft/fast-blazor/pull/75

The Grid itself supports dates, strings, numbers, etc. The Blazor wrapper supports item and cell templating so that you can put whatever you want into the grid. You can manually build the rows/cells or template them over an array of data items.

Sorting, filtering, and grouping are not built-in to the core Web Component at this time and so are not available in Blazor. Sorting and filtering should be possible to implement by using C# sort/filter code along with a data grid cell template for the UI. Grouping may be more complicated. I would invite the community to try these scenarios out and then provide us with some feedback that we can use to improve the next version of the grid. For core grid features like these, the best place to request or provide feedback is in the FAST monorepo, located here: https://github.com/microsoft/fast This allows us to improve the components so that the new features can be used by everyone, regardless of framework/library/language choice.

**Comment by hkusulja** [comment]
Thank you for the update.
However, the whole premises was > Microsoft Fluent UI web components > (using FAST) implement in Blazor.
Therefore, sorting and filtering is a must have, and I hope this will be updated and supported here.
Sorting is also mentioned here - https://github.com/microsoft/fast/issues/4576

**Comment by scomea** [comment]
> Therefore, sorting and filtering is a must have, and I hope this will be updated and supported here.

Yes, sorting and filtering is on the radar but not clear what that implementation will look like yet.  Note that authors can manipulate (ie. sort/filter) the array of rows they pass to the grid and the grid should respond. They can also customize cells/headers and hook up ui and handlers that could rearrange the row data on click. So, there is a fairly clear path to implement sorting and filtering now. I understand this is more difficult with Blazor interop than for a JS author.  

I do think we should have a way to bundle up some of the more advanced grid functionality so authors can have it "out of the box", but I'd like us to do so in a way that keeps the base data-grid component compact and fast for those that don't need it.    I don't yet have an opinion on the best way to do that - do we have specialized variant components that wrap data-grid and add functionality, can we do it with pre-made helper functions and templates?  Happy to hear suggestions.

I'm currently working on prototyping virtualization for data grid, tackling how to best integrate more advanced grid functionality is a good candidate for the next project.

**Comment by hkusulja** [comment]
well, it is ok to justify expectations. But again, since it was sait that point is Fluent UI web components in blazor. If you look the original - https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist , we are very far from it.

Just please align expectations and decide and say statement something like "this blazor fluent ui nuget will not implement such a functionality on controlls", and then, we know that need to look for 3rd party things (free or paid) like https://demos.telerik.com/blazor-ui/grid/overview , or maybe even https://www.blazorfluentui.net/detailsListPageBasic

**Comment by EisenbergEffect** [comment]
@hkusulja *We would like to enable these features in the grid* but do not know the best strategy for that yet or when the work will happen.

At present, the component does not build in sorting and filtering. If you need those *today* and aren't interested in handling it manually in Blazor, then you will need to look for a 3rd party control. That said, filtering and sorting in particular, should be only a few lines of code to plug into the grid using Blazor. This is likely a more efficient way to handle it than us building it in as well.

@vnbaaij Would you be willing to add another example to the DataGrid PR that demonstrates filtering and sorting? The approach would be to use standard C# APIs to filter/sort the List<T> in Blazor. Then probably add a text input to filter by some property and template out header cells with buttons that toggle sort. Thoughts?

**Comment by limefrogyank** [comment]
FYI, the sample for filtering and sorting has been done 😏
https://github.com/microsoft/fast-blazor/blob/375fc5b0c8456725464403f3f864bbb58628a3d5/examples/FluentUIServerSample/Components/FluentDataGridTest.razor#L37

![image](https://user-images.githubusercontent.com/7821384/136056100-339093c5-9a21-4a60-916f-a023574321e7.png)

**Comment by EisenbergEffect** [comment]
Closing this for now since we've got the basic grid in along with a demo that shows sorting and filtering. For additional features built-into the grid let's open feature-specific issues on the components repo here: https://github.com/microsoft/fast

**Comment by hkusulja** [comment]
@EisenbergEffect when will this sorting and filtering be part of NuGet package?
also, what about select row , including select all (checkbox) inside grid component?

just to align expectations, what about Fluent UI React > Microsoft Fast Fluent UI for Blazor (this repo) and DetalsList component and all of the features: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist

**Comment by scomea** [comment]
@hkusulja Conversations on closed issues can easily get lost :-).  You should not be dependent on anything being added to the package to follow the sorting/filtering samples as they are based on the current grid.  

As for adding a checkbox you can already define a custom cell with a checkbox similarly to this example which has a cell with a button - (https://github.com/microsoft/fast/blob/746ed487e8eb1ab2ede0ecdc09a6a11afc0baaba/packages/web-components/fast-components/src/data-grid/data-grid.stories.ts#L210)   You'd still have to figure how to track selected rows and style them.

**Comment by hkusulja** [comment]
@scomea i didn't want to open a new issue, instead i tagged people, but thx for the future tip.
Question here is that I want to relay on a package which will provide the components for our projects use.
We do not want to invent the wheel or start from the scratch or from mid.
We were originally looking for mentioned DetailsList from presented Fluent UI with above URL, but Microsoft implementation for .NET 6 / Blazor WASM and now we are here, and if you compare features, it is very very different (no modalselect) etc.
Of course, we can write everything by ourselves from scratch or partial work, but to be honest we expect this components to be finished so we can focus on "our stuff".
So, can you confirm me, just to align expectations, that this repo - microsoft/blazor-fast , will no longer invest (in near future) in datagrid and its features inside a component and package byitself?

**Comment by scomea** [comment]
I hear about DetailsList frequently, so I expect it is a scenario we'd want to address at some point, but I don't have any idea of time frame myself.
