### ISSUE TITLE
Fabric Core and Fluent UI

### ISSUE THREAD

**Issue by svengrav** [microsoft/fast-blazor#82]
# 💬 RFC

First of all: Cool work. Thanks for the project.  😉🥳

I don't know much about Fluent. In the docs there is a section Layout with for example Grid etc.. Is it also a goal to create these components with Razor as part of the project or is this something you will have to create in the future with "Plain" HTML. 

## 🔦 Context

https://developer.microsoft.com/en-us/fluentui#/styles/web/layout

**Comment by EisenbergEffect** [comment]
Good questions.

Our approach with FAST is to leverage web standards as much as possible and try not to abstract the standards away, especially when they are more powerful than the abstraction. This means that we are intentionally avoiding creating layout components at this time. Such components tend to abstract the more powerful core platform, resulting in a less powerful system and sometimes even more confusing. The modern CSS Grid and Flexbox layout features are very powerful and so we tend to encourage folks to learn and use those directly. With these features, it's not very hard to create a system of classes for yourself that meets exactly your application-specific needs.

The link you referenced for Fabric/Fluent is showing an older version of Fluent. So, we're not aiming to match what you see there today. Rather, we're building to the latest version of Fluent as seen in Windows 11. This is what all product groups are aligning to. The approach we are taking it to do that implementation as Web Components. Because this is a web standard, the components will work with any library or framework (or without any framework). The `fast-blazor` project provides a set of Blazor components that emit the standard web components. This allows us to have a single, platform standard implementation, while providing a native Blazor experience. We don't intend to re-write all the component details directly in Blazor as that would create a complete second implementation, with all the testing and maintenance requirements related to it. It might also perform worse than what we have today as the more course communication between Blazor and the Web Components is likely more efficient than the fine-grained DOM updates that direct implementation would result in.

Hopefully this answers your questions. I know it can be a bit confusing, especially with documentation of the previous design system still published and the latest not yet available. Here's a link where you can see all the Fluent Web Components: https://aka.ms/fluentwebcomponents Watch this for changes as the new Windows 11 updates will be shipping any day now 😉
