### ISSUE TITLE
rfc: add project template to nuget

### ISSUE THREAD

**Issue by blowin** [microsoft/fast-blazor#88]
This will make it easier to start using FastBlazor. Thanks.

**Comment by EisenbergEffect** [comment]
@blowin Any interest in helping us out by contributing that? It seems like a great idea to me.

**Comment by hkusulja** [comment]
So, can you please create a new dotnet project template, similar to default one:

`dotnet new blazorwasm`

but that includes the Fast-blazor in it with correct placement of FluentDesignSystemProvider and other things.
Since documentation, https://www.fast.design/docs/integrations/blazor/, is not so clear about end-result.

Reference for new / custom dotnet project template - https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template

**Comment by EisenbergEffect** [comment]
I'm going to close this out since we've merged the new project templates. They aren't released yet as we're working out some issues with publish and code signing. Coming soon!

**Comment by hkusulja** [comment]
@EisenbergEffect but why closing as resolved when it is not resolved. Please close once really resolved and available :) thank you for understanding

**Comment by EisenbergEffect** [comment]
We have a historic practice of closing the issue once the fix/feature is merged, not when the package related to that issue has been published to a package manager.

**Comment by hkusulja** [comment]
hmm, ok, tx for the info. So you are saying this is available and visible in master repo (feature merged and complete) now just waiting for nuget update/release deployment.

**Comment by vnbaaij** [comment]
@hkusulja Yes, correct. You can find the changes in the `templates` folder. In fact, the template packages are committed to the repo as well. So you don't even have to wait for the deployment. Follow the readme file in the folder to get started
